//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace megafon.ui.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("megafon.ui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;RSAKeyValue&gt;&lt;Modulus&gt;tK52RK6p8QCiCEbbYJ++iQmMnmST7R+FEQiBn34+8wu0sq7/kWcuHX9z+HzgDyEpEglwBerhxYy5FlSSgLxNghXzBHqbxaXd2wK+vHrfNE/XxwIboFuxLfgm2M3SiCjwy5OSOo94w/GJMNFhuPYLED5ZVk+KG7AYeK97yWSNSC0=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;0dTZ0YsIH99vb0XJ/ZINUhrUj9rjnK8v8gDrkUFvnvXbUemv+U7wfl1D9Yol3nEtHkeav2bFV7D9qnSQtEuJew==&lt;/P&gt;&lt;Q&gt;3G+vbWKT4MFjeQdOoZkuKocv7jvLw+IQsjYDFQFeGbFPuNdWbly7khraqhx5fnMeX61CNf0yAh5CLQUVhnMgdw==&lt;/Q&gt;&lt;DP&gt;QnIFm75MD1PAxNqzsPFb+ID4iKlG5GnxY8/4yKGRCCRQlCrNB8SAkXNVPt7FSSBLqkgAb9XKbg9k9GI/JGi7Gw==&lt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _private {
            get {
                return ResourceManager.GetString("_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;RSAKeyValue&gt;&lt;Modulus&gt;tK52RK6p8QCiCEbbYJ++iQmMnmST7R+FEQiBn34+8wu0sq7/kWcuHX9z+HzgDyEpEglwBerhxYy5FlSSgLxNghXzBHqbxaXd2wK+vHrfNE/XxwIboFuxLfgm2M3SiCjwy5OSOo94w/GJMNFhuPYLED5ZVk+KG7AYeK97yWSNSC0=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;/RSAKeyValue&gt;.
        /// </summary>
        internal static string _public {
            get {
                return ResourceManager.GetString("_public", resourceCulture);
            }
        }
    }
}
